---
build:
  jobs:
    post_install:
      - pip install poetry
      # VIRTUAL_ENV needs to be set manually for now.
      # See https://github.com/readthedocs/readthedocs.org/pull/11152/
      - 'VIRTUAL_ENV="$READTHEDOCS_VIRTUALENV_PATH" poetry install --all-extras --with=docs'
  os: ubuntu-22.04
  tools:
    python: '3.12'
sphinx:
  configuration: docs/conf.py
  fail_on_warning: true
version: 2
